name: Deploy to Cloud Run

on:
  workflow_dispatch: # solo se ejecuta manualmente desde GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gcloud'
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Generar revision-suffix Ãºnico
        id: revision
        run: echo "REV_SUFFIX=rev-$(date +%s)" >> $GITHUB_ENV

      - name: Deploy frontend
        run: |
          gcloud run deploy frontend \
            --image=docker.io/lacragh/frontend:latest \
             --revision-suffix="$REV_SUFFIX" \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars=AUTH_API_ADDRESS=https://auth-api-111693207847.us-central1.run.app,TODOS_API_ADDRESS=https://todos-api-111693207847.us-central1.run.app
            
      - name: Deploy auth-api
        run: |
          gcloud run deploy auth-api \
            --image=docker.io/lacragh/auth-api:latest \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars=AUTH_API_PORT=8000,USERS_API_ADDRESS=https://users-api-111693207847.us-central1.run.app,JWT_SECRET=PRFT
      - name: Deploy users-api
        run: |
          gcloud run deploy users-api \
            --image=docker.io/lacragh/users-api:latest \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars=SERVER_PORT=8083,JWT_SECRET=PRFT
        
      - name: Deploy todos-api
        run: |
          gcloud run deploy todos-api \
            --image=docker.io/lacragh/todos-api \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars=TODO_API_PORT=8082,JWT_SECRET=PRFT,REDIS_HOST=https://redis-111693207847.us-central1.run.app,REDIS_PORT=6379,REDIS_CHANNEL=log_channel


      
